#' get_apps_list fetch all apps
#'
#' @param token login token generated by \code{\link{get_login_token}}
#'
#' @return data.frame
#' @export
#'
get_apps_list <- function(token) {
  get_generic_list(token, 0, "/api/apps/v2",
                   c('type', 'id', 'name', 'addedAt', 'updatedAt'),
                   c('addedAt', 'updatedAt'))
}
