#' get_users_list fetch all users
#'
#' @param token login token generated by \code{\link{get_login_token}}
#' @param offset defailt 0, integer, where to start fetching users
#'
#' @return data.frame
#' @export
#'
get_users_list <- function(token, offset = 0) {
  get_generic_list(token, offset, "/api/users/v2",
                   c('type', 'id', 'addedAt', 'role', 'email', 'organization',
                     'language'),
                   c('addedAt'))
}


