#' get_usergroups_list fetch all usergroups
#'
#' @param token login token generated by \code{\link{get_login_token}}
#' @param offset defailt 0, integer, where to start fetching usergroups
#'
#' @return data.frame
#' @export
#'
get_usergroups_list <- function(token, offset = 0) {
  get_generic_list(token, offset, "/api/user-groups/v1",
                   c('type', 'id', 'name', 'created_at', 'updated_at'),
                   c('created_at', 'updated_at'))
}


