#' get_apps_list fetch all apps
#'
#' @param token login token generated by \code{\link{get_login_token}}
#' @param offset defailt 0, integer, where to start fetching apps
#'
#' @return data.frame
#' @export
#'
get_apps_list <- function(token, offset = 0) {
  get_generic_list(token, offset, "/api/apps/v2",
                   c('type', 'id', 'name', 'addedAt', 'updatedAt'),
                   c('addedAt', 'updatedAt'))
}
