#' get_apps_list fetch all apps
#'
#' @param token login token generated by \code{\link{get_login_token}}
#' @param offset defailt 0, integer, where to start fetching apps
#'
#' @return data.frame
#' @export
#'
get_apps_list <- function(token, offset = 0) {
  result <- get_apps_list_single(token, offset)
  result_data <- result$data

  if ((result$meta$total > result$data %>% nrow() + offset) ) {
    next_offset <- offset + MAX_LINES_PER_REQUEST_USERS_API()
    next_result <- get_apps_list(token, next_offset)
    result_data <- result_data %>% bind_rows(next_result)
  }

  result_data <- result_data %>%
    dplyr::mutate(
      addedAt = lubridate::ymd_hms(.data$addedAt),
      updatedAt = lubridate::ymd_hms(.data$updatedAt)
    )

  return(result_data)
}


#' single request for getting apps
#'
#' @param token login token generated by \code{\link{get_login_token}}
#' @param offset defailt 0, integer, where to start fetching apps
#'
#' @return data.frame

get_apps_list_single <- function(token, offset = 0) {

  url <- paste0(token$url, "/api/apps/v2")

  query <- list(
    offset = offset,
    limit  = MAX_LINES_PER_REQUEST_USERS_API()
  )

  result <- httr::GET(
    url = url,
    query = query,
    httr::add_headers(Authorization = paste0(token$token_type, " ",
                                             token$access_token)),
    httr::add_headers("Accept-Encoding" = "gzip, deflate"),
    httr::content_type("application/vnd.api+json")
  )

  if (httr::status_code(result) == 200) {
    json <- httr::content(result, "text", encoding = "utf8")

    from_json <- json %>% rjson::fromJSON(simplify = FALSE)
    meta <- from_json %>% extract2("meta")
    data <- from_json %>% extract2("data")

    if (length(data) > 0) {
      data <- data %>%  map_dfr(flatten)
    } else {
      data <- tibble(
        type = character(0),
        id = character(0),
        addedAt = character(0),
        role = character(0),
        email = character(0),
        organization = character(0),
        languange = character(0)
      )
    }
    return(list("data" = data, "meta" = meta))
  } else {
    warning(httr::content(result))
    return(NULL)
  }
}


